### ISSUE TITLE
Prioritize blocking rules against existing rules

### ISSUE THREAD

**Issue by jokogr** [ilikenwf/pg2ipset#3]
Hello,

How could someone use the ipset-update script at the same time with his own iptables rules? I have already a set of rules which deny all access except for a few ports and the pg2ipset match-set rules are added after them, so I suppose that the top port exception terminates the match.

**Comment by mynamewastaken** [comment]
You would have to modify either your existing rules, or the pg2ipset rules, or both. I locally modified my script to insert existing iptables rules that I need.

If you have 2 rules in a row that block tcp 80, the 2nd rule will never be reached.

**Comment by jokogr** [comment]
mynamewastaken,

You were right and for the time being, I have chosen to modify the ipset-update script.

Please have a look at jokogr/pg2ipset@89b61460666d5ccd5e048a03f434067429076696 and let me know in case you want me to create a pull request.

**Comment by mynamewastaken** [comment]
(I'm not the author of the repo, that's @ilikenwf )

I looked at your diff, and IMO, you are better off just maintaining those differences locally. Anytime you have your own iptables rules in addition to what the script adds, you're going to have to be careful about ordering.

**Comment by ilikenwf** [comment]
We could possibly add a check for a custom rules file, or even just load up /etc/iptables.up.d and flush the rules or something - you end up with duplicates if you just keep adding blocks.

**Comment by ilikenwf** [comment]
Now that I have read the rest, I understand the context. We could add, at the least, the option of appending or prepending the rules from the update script. 

Also something I should consider is making ULOG optional.
